### ISSUE TITLE
Inline component

### ISSUE THREAD

**Issue by metasoarous** [Odinodin/data-frisk-reagent#1]
This would make the context of the data you're inspecting much clearer (visually so, even) when you want to inspect more than one piece of data in a UI. This could even (perhaps) for some apps be used for default error components :-)

**Comment by Odinodin** [comment]
I think this is a great idea and it is basically supported already (see the badly named Root component), though I want to make it more explicit as well as document it.

**Comment by metasoarous** [comment]
Awesome! I'll try it out. Perhaps we can leave the issue around as a documentation (and perhaps renaming) request then.

**Comment by metasoarous** [comment]
@Odinodin Would you mind pushing an update to Clojars? This is causing some havoc with [datsys](https://github.com/metasoarous/datsys).

**Comment by Odinodin** [comment]
Sure thing, I'll deploy one later this evening when I get back home

/Odin

**Comment by metasoarous** [comment]
Awesome! Thanks!

**Comment by Odinodin** [comment]
0.2.5 is now deployed to Clojars :)

**Comment by metasoarous** [comment]
Awesome! Thanks!
