### ISSUE TITLE
Feature request: sort map keys

### ISSUE THREAD

**Issue by timgilbert** [Odinodin/data-frisk-reagent#17]
Once my data structures start to get fairly complex, it can be a little difficult to navigate down to the piece of it that I'm interested. It would be nice if data-frisk had an option to sort the keys in maps, rather than just presenting them in map sort order.

**Comment by Odinodin** [comment]
Good input. Is there a reason not to just always sort maps though?

**Comment by Odinodin** [comment]
Map keys are always sorted in 0.4.1. Thanks for the idea
