### ISSUE TITLE
Better organization of multiple "frisks"

### ISSUE THREAD

**Issue by metasoarous** [Odinodin/data-frisk-reagent#2]
Right it seems (correct me if I'm wrong) that you can only really frisk one data object at a time. This makes it difficult to inspect data nested at some place within an app, where the component with the data in question is representated more than once in the UI. While #1 addresses this to some degree, it does so at the expense of potentially wrecking the UI (why I think the overlay functionality of data-frisk is so valuable).

What would be ideal is for you to call something like `d/DataFriskShell` that would queue some data for inspection, and ultimately produce a single component with all of the inspected chunks of data organized in some way. Perhaps you could even drop in anchors that let the chunks of data you inspect point to the components with the data you're inspecting.

A hacky/partial/non-optimal implementation would probably still be helpful, but there's probably a lot you could do to make things really slick here.

**Comment by Odinodin** [comment]
The DataFriskShell component takes a list of arguments, each of which will be visualized separately in the shell. Is that what you were thinking about?

**Comment by metasoarous** [comment]
That assumes all those pieces of data exist at the same time in the same component. But if you want to frisk from some component that gets called multiple times (or from multiple components), you're out of luck as far as I can tell.

**Comment by Odinodin** [comment]
This is covered by the FriskInline component.
