### ISSUE TITLE
[Request] Add 'expand all' button

### ISSUE THREAD

**Issue by gadfly361** [Odinodin/data-frisk-reagent#3]
Would be nice to have an 'expand all' button next to 'collapse all' :)

**Comment by Odinodin** [comment]
Feature added 🎺

**Comment by gadfly361** [comment]
Woohoo!! Thank you, much appreciated :)

**Comment by flexsurfer** [comment]
Awesome! :)

**Comment by flexsurfer** [comment]
@Odinodin doesn't work for r/atom nodes
