### ISSUE TITLE
Ability to modify state

### ISSUE THREAD

**Issue by timothypratley** [Odinodin/data-frisk-reagent#6]
Have you given any thought to allowing users to change the values?
(when viewing ratoms or mutable things)

**Comment by timothypratley** [comment]
https://github.com/Odinodin/data-frisk-reagent/pull/7

This way you can update values as well as observe them.
My use case is that I am building SVG animations that control to values stored in a ratom, and this allows me to interactively adjust them.

**Comment by Odinodin** [comment]
Awesome, thanks for the pull request. I just merged it in.

**Comment by timothypratley** [comment]
Groovy! Glad you liked it. Thank you for making frisk, I find it very useful.
