### ISSUE TITLE
React-with-addons dependency

### ISSUE THREAD

**Issue by Deraen** [Odinodin/data-frisk-reagent#8]
Is react-with-addons really necessary? Looks like it is not because it is not `:require`d anywhere.

Currently most users will end up with multiple Reacts (in classpath) because Reagent etc. depend on normal version and readme here doesn't ask user to exclude those. At minimum the readme should state that user has to add exclude normal React.

Even better would be to use normal React, or not depend on React directly and just depend on Reagent.

**Comment by Odinodin** [comment]
Good point, I'll put it on my TODO list. Also, pull requests are welcome :)
